version: '2.2'
services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: star-wars-db
    ports:
      - "5432:5432"
    networks:
      - starwars-network

  spring-app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - starwars-network

networks:
  starwars-network:
    driver: bridge